#!/bin/bash

readonly connector_home="$HOME"/git/tableau-connector
readonly connector_tdvt_dir="$connector_home"/tdvt
readonly tdvt_log_dir="$TEMP"/tdvt_logs
readonly python='python'
readonly tdvt_module='tdvt.tdvt'
readonly connector='exasol_odbc'

create_log_dir() {
    if [[ ! -x "$tdvt_log_dir" ]]; then
        echo "Creating Log file directory: $tdvt_log_dir"
        mkdir -p "$tdvt_log_dir"
    fi
}

run_tests() {
    "$python" -m "$tdvt_module" run "$connector"
}

move_logs() {
    echo "Moving log files from '$connector_tdvt_dir' to '$tdvt_log_dir'"
    mv "$connector_tdvt_dir"/tdvt_log_combined.txt "$connector_tdvt_dir"/test_results_combined.csv \
	    "$connector_tdvt_dir"/tabquery_logs.zip "$connector_tdvt_dir"/tdvt_actuals_combined.zip \
	    "$connector_tdvt_dir"/tdvt_output_combined.json \
	    "$tdvt_log_dir"/
}

create_log_dir
run_tests
echo
move_logs
