name: CI Build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: "javascript-test/package-lock.json"

      - name: Run JavaScript tests
        run: |
          cd javascript-test
          npm ci
          npm run test

      - name: Build connectors
        run: ./tools/package_connector.sh

      - name: Upload unsigned connectors
        uses: actions/upload-artifact@v3
        with:
          name: Unsigned Exasol Tableau Connectors
          path: target/exasol_*.taco

      - name: Retrieve code signing certificate
        run: echo $CODE_SIGNING_CERTIFICATE_BASE64 | base64 --decode > target/cert.p12
        env:
          CODE_SIGNING_CERTIFICATE_BASE64: ${{ secrets.CODE_SIGNING_CERTIFICATE_BASE64 }}

      - name: Retrieve code signing certificate chain
        run: echo $CODE_SIGNING_CERTIFICATE_CHAIN_BASE64 | base64 --decode > target/cert_chain.p7b
        env:
          CODE_SIGNING_CERTIFICATE_CHAIN_BASE64: ${{ secrets.CODE_SIGNING_CERTIFICATE_CHAIN_BASE64 }}

      - name: Sign connectors
        run: ./tools/sign_connector.sh target/cert.p12 target/cert_chain.p7b
        env:
          CODE_SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}

      - name: Upload signed connectors
        uses: actions/upload-artifact@v3
        with:
          name: Signed Exasol Tableau Connectors
          path: target/tableau-exasol-connector-*.taco

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 11
          cache: "maven"

      - name: Project Keeper Verify
        run: mvn --batch-mode -DtrimStackTrace=false --projects . test com.exasol:project-keeper-maven-plugin:verify
