name: CI Build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

    - uses: actions/setup-node@v2
      with:
        node-version: 16.x

    - name: Cache npm files
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-

    - name: Run JavaScript tests
      run: |
        cd javascript-test
        npm ci
        npm run test

      - name: Build connectors
        run: ./tools/package_connector.sh

      - name: Upload connectors
        uses: actions/upload-artifact@v2
        with:
          name: Exasol Tableau Connectors
          path: target/*.taco

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run unit tests
        run: mvn --batch-mode test -DtrimStackTrace=false
