name: CI Build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache npm files
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Run JavaScript tests
        run: |
          cd javascript-test
          npm ci
          npm run test

      - name: Build connectors
        run: ./tools/package_connector.sh

      - name: Upload unsigned connectors
        uses: actions/upload-artifact@v2
        with:
          name: Unsigned Exasol Tableau Connectors
          path: target/exasol_*.taco

      - name: Retrieve code signing certificate
        run: echo $CODE_SIGNING_CERTIFICATE_BASE64 | base64 --decode > target/cert.pfx
        env:
          CODE_SIGNING_CERTIFICATE_BASE64: ${{ secrets.CODE_SIGNING_CERTIFICATE_BASE64 }}

      - name: Sign connectors
        run: ./tools/sign_connector.sh target/cert.pfx
        env:
          CODE_SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}

      - name: Upload signed connectors
        uses: actions/upload-artifact@v2
        with:
          name: Signed Exasol Tableau Connectors
          path: target/tableau-exasol-connector-*.taco

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'

      - name: Run unit tests
        run: mvn --batch-mode -DtrimStackTrace=false --projects . test com.exasol:project-keeper-maven-plugin:verify
