name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: "Assets upload URL"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build connectors
        run: ./tools/package_connector.sh

      - name: Retrieve code signing certificate
        run: echo $CODE_SIGNING_CERTIFICATE_BASE64 | base64 --decode > target/cert.pfx
        env:
          CODE_SIGNING_CERTIFICATE_BASE64: ${{ secrets.CODE_SIGNING_CERTIFICATE_BASE64 }}

      - name: Sign connectors
        run: ./tools/sign_connector.sh target/cert.pfx
        env:
          CODE_SIGNING_CERTIFICATE_PASSWORD: ${{ secrets.CODE_SIGNING_CERTIFICATE_PASSWORD }}

      - name: Generate sha256sum files
        run: |
          cd target
          find . -maxdepth 1 -name "tableau-exasol-connector-*.taco" -exec bash -c 'sha256sum {} > {}.sha256' \;

      - name: Upload signed connectors
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/tableau-exasol-connector-*.taco

      - name: Upload sha256sum files
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.inputs.upload_url }}
          asset_path: target/*.sha256
